# in case need to build from a local backend
# this file would be located here: bitclout/run/backend/Dockerfile
# and would be referenced when running bitclout/run/run.sh

FROM docker.io/bitclout/backend:latest
WORKDIR /bitclout/bin
CMD ./backend run
